### ISSUE TITLE
Not working with ApacheJMeter:3.3 java.lang.NoClassDefFoundError: Could not initialize class org.apache.jmeter.gui.util.MenuFactory

### ISSUE THREAD

**Issue by sardesh** [Netflix/CassJMeter#23]
This is not compatible with ApacheJmeter3.3 giving the following error when starting Jmeter
ERROR o.a.j.JMeter: Uncaught exception: 
java.lang.NoClassDefFoundError: Could not initialize class org.apache.jmeter.gui.util.MenuFactory
	at org.apache.jmeter.control.gui.TestPlanGui.createPopupMenu(TestPlanGui.java:93) ~[ApacheJMeter_core.jar:3.3 r1808647]

**Comment by amirAlamian** [comment]
try to change the theme of your jmeter. Options>look and feel and select system theme.
